id: 142e9532fa0e4d5ab66e1d6318406d81
initial_creation_type: ocr
source_metadata:
  volumes:
    7b0506a145e0478788e644889928b1b9:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: དཔའ་བོ་གཅིག་པའི་སྒྲུབ་ཐབས།
      total_pages: 2107
      volume_number: 11
